---
# This playbook deploys JBoss servers.

- hosts: domain_controller
  roles:
    - domain-controller

- hosts: application_servers
  roles:
    - application-server

- hosts: loadbalancer_servers
  roles:
    - load-balancer
