---

- name: Start domain
  shell: "export JBOSS_HOME={{ jboss_home }}; {{ jboss_home }}/bin/domain.sh --host-config=host-slave.xml -c=domain-slave.xml -Djboss.domain.master.address={{ domain_controller_address }}"
