---

- name: Create admin user for JBoss
  tags: configure
  shell: "export JBOSS_HOME={{ jboss_home }}; {{ jboss_home }}/bin/add-user.sh -u admin -p {{ jboss_admin_password }} -s"

- name: Add CLI configuration script
  tags: configure
  template: src=mod-cluster.cli dest={{ ansible_user_dir }} owner={{ jboss_user }} group={{ jboss_group }} mode=644

- name: Add host-master.xml
  tags: configure
  template: src=host-master.xml dest={{ ansible_user_dir }} owner={{ jboss_user }} group={{ jboss_group }} mode=644

- name: Add start.sh
  tags: configure
  template: src=start.sh dest={{ ansible_user_dir }} owner={{ jboss_user }} group={{ jboss_group }}

- name: Apply configuration
  tags: configure
  shell: "export JBOSS_HOME={{ jboss_home }}; {{ jboss_home }}/bin/jboss-cli.sh --file={{ ansible_user_dir }}/mod-cluster.cli"
