---

- name: Create admin user for JBoss
  shell: "export JBOSS_HOME={{ jboss_home }}; {{ jboss_home }}/bin/add-user.sh -u admin -p {{ jboss_admin_password }} -s"

- name: Add CLI configuration script
  template: src=mod-cluster.cli dest={{ jboss_home }}/domain/configuration/ owner={{ jboss_user }} group={{ jboss_group }} mode=644

- name: Add host-master.xml
  template: src=host-master.xml dest={{ jboss_home }}/domain/configuration/ owner={{ jboss_user }} group={{ jboss_group }} mode=644

- name: Add domain master
  template: src=domain.xml dest={{ jboss_home }}/domain/configuration/ owner={{ jboss_user }} group={{ jboss_group }} mode=644

- name: Add start.sh
  template: src=start.sh dest={{ ansible_user_dir }} owner={{ jboss_user }} group={{ jboss_group }}

- name: open ports
  ansible.posix.firewalld: port={{ item }}/tcp permanent=yes state=enabled
  loop:
     - 9990
     - 9999
     - 7600

- name: open ports
  ansible.posix.firewalld: port={{ item }}/udp permanent=yes state=enabled
  loop:
     - 23364

#- name: Apply configuration
#  tags: configure
#  shell: "export JBOSS_HOME={{ jboss_home }}; {{ jboss_home }}/bin/jboss-cli.sh --file={{ ansible_user_dir }}/mod-cluster.cli"
