---

- name: Start domain
  tags: start
  shell: "export JBOSS_HOME={{ jboss_home }}; {{ jboss_home }}/bin/domain.sh --host-config=host-master.xml -Djboss.bind.address.management={{ domain_controller_address }}"
