---

- name: Start domain
  shell: "export JBOSS_HOME={{ jboss_home }}; nohup ${JBOSS_HOME}/bin/domain.sh --host-config=host-master.xml -Djboss.bind.address.management={{ domain_controller_address }} 2>&1 &"
